// <auto-generated />
namespace OBTS.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddContactDetial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddContactDetial));
        
        string IMigrationMetadata.Id
        {
            get { return "201512210726555_AddContactDetial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
